name: mvgutils
channels:
  - conda-forge
  - pytorch
  - fastai
  - pytorch
dependencies:
  - python=3.9
  - scipy
  - numpy
  - PyYAML
  - tqdm
  - matplotlib
  - seaborn
  - pandas
  - Pillow
  - ipykernel
  - fastcore
  - nbdev
  - easydict
  - pip
  - pytorch=1.12.1      
  - torchvision=0.13.1  
  - pip:
    # - torch==1.7.1+cu110  torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html
#     - --find-links https://download.pytorch.org/whl/torch_stable.html
#     - torch==1.7.1+cu110 
#     - torchvision==0.8.2+cu110 
    - ipyvolume==0.6.0a10
    - opencv-python<4.6
    - pyransac3d

    
